# Generated by Django 2.1.5 on 2021-07-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210728_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='like',
        ),
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
